# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Track & Song
email: tracknsong@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  To be a good web developer., Write down what I aquired in everyday working process.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skintest.github.io/" # the base hostname & protocol for your site
twitter_username: skintaste
github_username:  skinTest
excerpt_separator: <!-- more --> # this means, in each post, things before this will be grabbed into excerpt

# Build settings
markdown: kramdown
